#!/bin/bash

# CLI GUI Function
print_board() {
  echo ""
  echo "    Spaces Cleared: "$CLRSPC"   Flags Placed: "${!FLGARR[@]}
  echo ""
  echo "          1 2 3 4 5 6 7 8 9"
  echo "         %%%%%%%%%%%%%%%%%%%"
  for y in $(seq 0 10); do
    ROWARR=()
    for x in $(seq 0 8); do
      case $CELLTYPE in
      SAFE)
        ROWARR[x]="O"
        ;;
      FLAG)
        ROWARR[x]="F"
        ;;
      UNGES)
        ROWARR[x]="X"
        ;;
      esac
    done
    echo "       "${ALPH[y]}" |"${ROWARR[*]}"|"
  done
  echo "         %%%%%%%%%%%%%%%%%%%"
  echo ""
}

# Setup Board and variables
TARGETBOM=10
BOMNUM=0
BOMARR=(00)
CLRSPC=0
GUSTRK=()
GUSNUM=0
CELLTYPE="UNGES"
FLAGARR=()
ALPH=("A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K")

#Generate Bomb Locations
while test $BOMNUM -lt $TARGETBOM; do

  #Run while less than target number of bombs
  GOODCHECK=1                            # Reset Checker
  BOMLOC=$((RANDOM % (100 - 1 + 1) + 1)) # Generate new random bomb position

  # Test if single digit number for formatting
  if test $BOMLOC -lt 10; then # If bomb location number is < 10
    BOMLOC="0"$BOMLOC          # add 0 to front of single digit number
  fi

  # Test if bomb is in repeat location
  for i in $( # for every bomb already placed
    seq 0 $((BOMNUM - 1))
  ); do
    if test $BOMLOC -eq ${BOMARR[i]}; then # if the new bomb is loacted in repeat spot
      GOODCHECK=0                          # Trip checker variable
    else                                   # if bomb location unique
      :                                    # continue through loop
    fi
  done

  # Test if checker has been tripped
  if test $GOODCHECK -eq 1; then # If checker is still good
    BOMARR[$BOMNUM]=$BOMLOC      # Add new location to array
    BOMNUM=$((BOMNUM + 1))       # Add to bomb count
  fi

done

while test $CLRSPC -lt 90; do
  print_board
  echo "      What is your next guess? :"
  read GUESSLOC
  GUESSX=${GUESSLOC:0:1}
  GUESSY=${GUESSLOC:1:2}
  ERRORCKX=0
  ERRORCKY=0
  ERRORCK=0


  if [[ $GUESSX =~ ^[+-]?[0-9]+$ ]]; then
    :
  else
    echo "!!X guess is not a number!!" 
    ERRORCKX=1
  fi

  if test $ERRORCKX -eq 0; then
    if test $GUESSX -lt 1; then
      echo "!!0 is not on the board!!"
      ERRORCKX=1
    fi
  fi


  if [[ $GUESSY =~ ^[+-]?[0-9]+$ ]]; then
    echo "!!Y guess is not a letter"
    ERRORCKY=1
  else
    :
  fi

  if test $ERRORCKY -eq 0; then
    ERROCKY=1
    for t in $(seq 0 10); do
    	if  [[ $GUESSY == ${ALPH[t]} ]]; then
      		ERRORCKY=0
    	fi
    done
    if test $ERRORCKY -eq 1;then
	echo "!!Y guess is not in range!!"
    fi
  fi



  while test $ERRORCK -eq 1; do
    :
  done

  #clear
done

# TEST OUTPUT
#echo $BOMNUM
#echo $BOMLOC
#echo ${BOMARR[*]}
#print_board
