#!/bin/bash

#BASH MINESWEEPER
#by: Zane Rollins
#date: 2/4/2026
#Minesweeper that can be played in the terminal via the bash shell

clear

# CLI GUI Function
print_board() {
  echo ${BOMARR[*]}
  echo ""
  echo "    Spaces Cleared: "$CLRSPC"   Flags Placed: "${#FLGARR[@]}
  echo ""
  echo "          1 2 3 4 5 6 7 8 9"
  echo "         %%%%%%%%%%%%%%%%%%%"
  for y in $(seq 0 10); do
    ROWARR=()
    for x in $(seq 0 8); do
      CELLTYPE=()
      CELLNUM=$(((x + 1) + (y * 9)))
      if test $CELLNUM -lt 10; then # If bomb location number is < 10
        CELLNUM="0"$CELLNUM         # add 0 to front of single digit number
      fi
      for n in $(seq 0 $((CLRSPC - 1))); do
        if [[ "$CELLNUM" == "${GUSTRK[n]}" ]]; then
          CELLTYPE="SAFE"
        fi
      done

      for n in $(seq 0 $((CLRSPC - 1))); do
        if [[ "$CELLNUM" == "${FLGARR[n]}" ]]; then
          CELLTYPE="FLAG"
        fi
      done

      case $CELLTYPE in
      SAFE)
        NEARBOM=0

        if
          [[ "$CELLNUM" == "01" ]] || [[ "$CELLNUM" == "02" ]] ||
            [[ "$CELLNUM" == "10" ]] || [[ "$CELLNUM" == "11" ]] ||
            [[ "$CELLNUM" == "19" ]] || [[ "$CELLNUM" == "20" ]] ||
            [[ "$CELLNUM" == "28" ]] || [[ "$CELLNUM" == "29" ]] ||
            [[ "$CELLNUM" == "37" ]] || [[ "$CELLNUM" == "38" ]] ||
            [[ "$CELLNUM" == "46" ]] || [[ "$CELLNUM" == "47" ]] ||
            [[ "$CELLNUM" == "55" ]] || [[ "$CELLNUM" == "56" ]] ||
            [[ "$CELLNUM" == "64" ]] || [[ "$CELLNUM" == "65" ]] ||
            [[ "$CELLNUM" == "73" ]] || [[ "$CELLNUM" == "74" ]] ||
            [[ "$CELLNUM" == "82" ]] || [[ "$CELLNUM" == "83" ]] ||
            [[ "$CELLNUM" == "91" ]] || [[ "$CELLNUM" == "92" ]]
        then
          NEARARR=($((CELLNUM - 9)) $((CELLNUM - 8)) $((CELLNUM + 1)) $((CELLNUM + 9)) $((CELLNUM + 10)))
        elif
          [[ "$CELLNUM" == "08" ]] || [[ "$CELLNUM" == "09" ]] ||
            [[ "$CELLNUM" == "17" ]] || [[ "$CELLNUM" == "18" ]] ||
            [[ "$CELLNUM" == "26" ]] || [[ "$CELLNUM" == "27" ]] ||
            [[ "$CELLNUM" == "35" ]] || [[ "$CELLNUM" == "36" ]] ||
            [[ "$CELLNUM" == "44" ]] || [[ "$CELLNUM" == "45" ]] ||
            [[ "$CELLNUM" == "53" ]] || [[ "$CELLNUM" == "54" ]] ||
            [[ "$CELLNUM" == "62" ]] || [[ "$CELLNUM" == "63" ]] ||
            [[ "$CELLNUM" == "71" ]] || [[ "$CELLNUM" == "72" ]] ||
            [[ "$CELLNUM" == "80" ]] || [[ "$CELLNUM" == "81" ]] ||
            [[ "$CELLNUM" == "89" ]] || [[ "$CELLNUM" == "90" ]] ||
            [[ "$CELLNUM" == "98" ]] || [[ "$CELLNUM" == "99" ]]
        then
          NEARARR=($((CELLNUM - 9)) $((CELLNUM - 8)) $((CELLNUM + 1)) $((CELLNUM + 9)) $((CELLNUM + 10)))
        else
          NEARARR=($((CELLNUM - 10)) $((CELLNUM - 9)) $((CELLNUM - 8)) $((CELLNUM - 1)) $((CELLNUM + 1)) $((CELLNUM + 8)) $((CELLNUM + 9)) $((CELLNUM + 10)))
        fi

        for p in $(seq 0 ${#NEARARR[@]}); do
          for o in $(seq 0 $((BOMNUM - 1))); do
            if [[ "${NEARARR[p]}" == "${BOMARR[o]}" ]]; then
              NEARBOM=$((NEARBOM + 1))
            fi
          done
        done

        ROWARR[x]=$NEARBOM
        ;;
      FLAG)
        ROWARR[x]="F"
        ;;
      *)
        ROWARR[x]="X"
        ;;
      esac
    done
    echo "       "${ALPH[y]}" |"${ROWARR[*]}"|"
  done
  echo "         %%%%%%%%%%%%%%%%%%%"
  echo ""
}

death_screen() {
  clear
  echo "           YOU FAILED :(        "
  echo ""
  echo "          %%%%%%%%%%%%%%%       "
  echo "       %%%%%%%%%%%%%%%%%%%%%    "
  echo "      %%%%%%%%%%%%%%%%%%%%%%%   "
  echo "      %%%%   %%%%%%%%%  %%%%%   "
  echo "      %%%%   %%%%%%%%%  %%%%%   "
  echo "      %%%%%%%%%%% %%%%%%%%%%%   "
  echo "        %%%%%%%%   %%%%%%%%     "
  echo "          %%%%%%%%%%%%%%%       "
  echo "          %%%%%%%%%%%%%%%       "
  echo "           %%% %% %% %%%        "
  echo "           %%% %% %% %%%        "
  echo "           %%% %% %% %%%        "
  echo ""
  echo "    Spaces Cleared: "$CLRSPC"   Flags Placed: "${!FLGARR[@]}
  DEAD=1
}

convert_coords() {
  FIRSTIN=${1:0:1}
  SECONDIN=${1:1:2}

  for k in $(seq 0 10); do
    if [[ "$SECONDIN" == "${ALPH[k]}" ]]; then
      YINDEX=$k
    fi
  done

  ROWADD=$((9 * YINDEX))
  COLMADD=$((ROWADD + FIRSTIN))
  GUESSLOC=$((COLMADD))
  #echo $GUESSLOC
  if test $GUESSLOC -lt 10; then # If bomb location number is < 10
    GUESSLOC="0"$GUESSLOC        # add 0 to front of single digit number
  fi
}

# Setup Board and variables
TARGETBOM=10
BOMNUM=0
BOMARR=(00)
CLRSPC=0
GUSTRK=()
GUSNUM=0
CELLTYPE="UNGES"
FLGARR=()
ALPH=("A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K")
ERR="     What is your guess? :"
DEAD=0

#Generate Bomb Locations
while test $BOMNUM -lt $TARGETBOM; do

  #Run while less than target number of bombs
  GOODCHECK=1                           # Reset Checker
  BOMLOC=$((RANDOM % (99 - 1 + 1) + 1)) # Generate new random bomb position

  # Test if single digit number for formatting
  if test $BOMLOC -lt 10; then # If bomb location number is < 10
    BOMLOC="0"$BOMLOC          # add 0 to front of single digit number
  fi

  # Test if bomb is in repeat location
  for i in $( # for every bomb already placed
    seq 0 $((BOMNUM - 1))
  ); do
    if test $BOMLOC -eq ${BOMARR[i]}; then # if the new bomb is loacted in repeat spot
      GOODCHECK=0                          # Trip checker variable
    fi
  done

  # Test if checker has been tripped
  if test $GOODCHECK -eq 1; then # If checker is still good
    BOMARR[$BOMNUM]=$BOMLOC      # Add new location to array
    BOMNUM=$((BOMNUM + 1))       # Add to bomb count
  fi

done

while test $CLRSPC -lt 90 && test $DEAD -eq 0; do
  clear
  print_board
  echo "       "$ERR
  #echo ${BOMARR[@]}
  read GUESSLOC

  GUESSX=${GUESSLOC:0:1}
  GUESSY=${GUESSLOC:1:2}
  ERRORCKX=0
  ERRORCKY=0
  ERRORCK=0

  if [[ $GUESSX =~ ^[+-]?[0-9]+$ ]]; then
    :
  else
    ERR="!!X guess is not a number!!"
    ERRORCKX=1
  fi

  if test $ERRORCKX -eq 0; then
    if test $GUESSX -lt 1; then
      ERR="!!0 is not on the board!!"
      ERRORCKX=1
    fi
  fi

  if [[ $GUESSY =~ ^[+-]?[0-9]+$ ]]; then
    ERR="!!Y guess is not a letter"
    ERRORCKY=1
  else
    :
  fi

  if test $ERRORCKY -eq 0; then
    ERRORCKY=1
    for t in $(seq 0 10); do
      if [[ "$GUESSY" == "${ALPH[t]}" ]]; then
        ERRORCKY=0
      fi
    done
    if test $ERRORCKY -eq 1; then
      ERR="!!Y guess is not in range!!"
    fi
  fi

  for n in $(seq 0 $((CLRSPC - 1))); do
    if [[ "$GUESSLOC" == "${GUSTRK[n]}" ]]; then
      ERRORCK=1
      ERR="!!Space has already been cleared!!"
    fi
  done

  convert_coords $GUESSLOC
  if test $ERRORCKY -eq 1 || test $ERRORCKX -eq 1 || test $ERRORCK -eq 1; then
    :
  else

    for m in $(seq 0 $((TARGETBOM - 1))); do
      if [[ "$GUESSLOC" == "${BOMARR[m]}" ]]; then
        death_screen
      else
        ERR="     Which space to clear? :"
      fi
    done
    GUSTRK[$CLRSPC]=$GUESSLOC
    CLRSPC=$((CLRSPC + 1))
  fi
done

# TEST OUTPUT
#echo $BOMNUM
#echo $BOMLOC
#echo ${BOMARR[*]}
#print_board
